define([], function () {
  return {
    // Property pane settings
    "PropertyPaneDescription": "Your quiz settings",
    "BasicGroupName": "General Settings",
    "TitleFieldLabel": "Quiz Title",
    "ListNameFieldLabel": "Questions List Name",
    "ResultsListNameFieldLabel": "Results List Name",
    "QuestionsPerPageFieldLabel": "Questions per page",
    "DescriptionFieldLabel": "Description",

    // Environment strings
    "AppLocalEnvironmentOffice": "Running locally in Office",
    "AppOfficeEnvironment": "Running in Office environment",
    "AppLocalEnvironmentOutlook": "Running locally in Outlook",
    "AppOutlookEnvironment": "Running in Outlook environment",
    "AppLocalEnvironmentTeams": "Running locally in Teams",
    "AppTeamsTabEnvironment": "Running in Teams environment",
    "UnknownEnvironment": "Unknown environment",
    "AppLocalEnvironmentSharePoint": "Running locally in SharePoint",
    "AppSharePointEnvironment": "Running in SharePoint environment",
    
    // Quiz property pane
    "QuizQuestionsTitle": "Quiz Questions",
    "AddQuestionButtonText": "Add Question",
    "ImportButtonText": "Import",
    "ShuffleQuestionsButtonText": "Shuffle Questions",
    "FilterQuestionsButtonText": "Filter Questions",
    "SortQuestionsButtonText": "Sort Questions",
    "DeleteAllQuestionsButtonText": "Delete All Questions",
    "NoQuestionsMessage": "No questions have been added yet. Click 'Add Question' to create your first question or 'Import' to import questions.",
    "QuestionAddedSuccess": "Question added successfully",
    "QuestionUpdatedSuccess": "Question updated successfully",
    "QuestionsImportedSuccess": "{0} questions imported successfully",
    "AllQuestionsDeletedSuccess": "All questions deleted successfully",
    "QuestionDeletedSuccess": "Question deleted successfully",
    "QuestionsRandomizedSuccess": "Questions randomized successfully",

    // Add/Edit Question dialog
    "AddNewQuestionTitle": "Add New Question",
    "EditQuestionTitle": "Edit Question",
    "QuestionTabText": "Question",
    "AdditionalInfoTabText": "Additional Info",
    "QuestionTitleLabel": "Question Title",
    "QuestionTitlePlaceholder": "Enter your question title here",
    "QuestionDescriptionLabel": "Question Description (Optional)",
    "QuestionDescriptionPlaceholder": "Add detailed question text, instructions, or context here...",
    "QuestionTypeLabel": "Question Type",
    "CategoryLabel": "Category",
    "CategoryPlaceholder": "Select or add category",
    "NewCategoryLabel": "New Category",
    "NewCategoryPlaceholder": "Enter new category",
    "ChoicesLabel": "Choices (select the correct answer)",
    "ChoiceMultiSelectLabel": "Choices (select all correct answers)",
    "CorrectAnswerTFLabel": "Select the correct answer:",
    "ChoicePrefix": "Choice",
    "CorrectAnswerLabel": "Correct Answer",
    "CorrectAnswerPlaceholder": "Enter the correct answer",
    "CaseSensitiveLabel": "Case sensitive",
    "PointsLabel": "Points",
    "ExplanationLabel": "Explanation (Optional)",
    "ExplanationPlaceholder": "Enter an explanation for the correct answer",
    "SaveQuestionButtonText": "Save Question",
    "UpdateQuestionButtonText": "Update Question",
    "PreviewButtonText": "Preview",
    "ResetButtonText": "Reset",
    "CancelButtonText": "Cancel",
    
    // Validation messages
    "ValidationQuestionTitleRequired": "Question title is required.",
    "ValidationCategoryRequired": "Please select or enter a category.",
    "ValidationMinChoicesRequired": "At least 2 valid choices are required.",
    "ValidationCorrectChoiceRequired": "Please mark at least one choice as correct.",
    "ValidationShortAnswerRequired": "Please enter the correct answer for the short answer question.",
    "ValidationPointsPositive": "Points must be a positive number.",
    
    // Question Preview
    "QuestionPreviewTitle": "Question Preview",
    "PreviewNoAnswer": "No answer provided",
    "PreviewCorrectAnswerLabel": "Correct Answer:",
    "PreviewCaseSensitiveInfo": "Answers are case sensitive",
    "PreviewExplanationLabel": "Explanation:",
    "PreviewNotAvailable": "Preview not available for this question type.",
    "PreviewCloseButton": "Close",
    
    // Import Questions dialog
    "ImportQuestionsTitle": "Import Questions",
    "ImportQuestionsDescription": "Import questions from CSV or JSON format",
    "ImportFormatLabel": "Import Format",
    "CSVFormatOption": "CSV Format",
    "JSONFormatOption": "JSON Format",
    "DefaultCategoryLabel": "Default Category (optional)",
    "NoneCategoryOption": "None",
    "NewCategoryOption": "Add new category",
    "NewCategoryNameLabel": "New Category Name",
    "UploadFileLabel": "Upload File",
    "UseTemplateButton": "Use {0} Template",
    "CSVFormatGuidelinesTitle": "CSV Format Guidelines",
    "CSVFormatGuidelinesText": "CSV files should include headers for \"Question\", \"Category\", \"Type\", \"Option 1\", \"Option 2\", etc., and \"Correct Answer\". The correct answer can be the option number or exact option text.",
    "JSONFormatGuidelinesTitle": "JSON Format Guidelines",
    "JSONFormatGuidelinesText": "JSON should be an array of question objects with properties like \"title\", \"category\", \"type\", and \"choices\" (an array of choice objects with \"text\" and \"isCorrect\" properties).",
    "CSVContentLabel": "CSV Content",
    "JSONContentLabel": "JSON Content",
    "CSVContentPlaceholder": "Paste CSV content here...",
    "JSONContentPlaceholder": "Paste JSON content here...",
    "ImportQuestionsButtonText": "Import Questions",
    "ProcessingLabel": "Processing...",
    "ImportErrorMessage": "Error importing questions. Please try again.",
    "NoQuestionsFoundError": "No valid questions found to import.",
    "ImportContentRequiredError": "Please provide content to import.",
    
    // Filter and sort
    "FilterQuestionsTitle": "Filter Questions",
    "SortQuestionsTitle": "Sort Questions",
    "SelectFilterPlaceholder": "Select filter",
    "AllQuestionsFilter": "All Questions",
    "SelectSortMethodPlaceholder": "Select sorting method",
    "TitleAscSortOption": "Title (A-Z)",
    "TitleDescSortOption": "Title (Z-A)",
    "CategoryAscSortOption": "Category (A-Z)",
    "CategoryDescSortOption": "Category (Z-A)",
    "ApplyButtonText": "Apply",
    
    // Bulk delete
    "ConfirmBulkDeleteTitle": "Confirm Bulk Delete",
    "ConfirmBulkDeleteText": "Are you sure you want to delete all {0} questions? This action cannot be undone.",
    "DeleteButtonText": "Delete",
    
    // Quiz Results
    "QuizResultsTitle": "Quiz Results",
    "SubmittingLabel": "Submitting your results...",
    "SuccessDefaultMessage": "Your score has been successfully recorded!",
    "ScoreLabel": "Score",
    "ScoreDetailsTemplate": "You answered {0} out of {1} points correctly.",
    "ExcellentScoreDefaultMessage": "Excellent! You have mastered this topic!",
    "GoodScoreDefaultMessage": "Good job! You have a solid understanding.",
    "AverageScoreDefaultMessage": "Not bad. There's room for improvement.",
    "PoorScoreDefaultMessage": "Keep studying. You'll get better with practice.",
    "SummaryTabText": "Summary",
    "DetailedResultsTabText": "Detailed Results",
    "RetakeQuizButtonText": "Retake Quiz",
    "ViewDetailedResultsButtonText": "View Detailed Results",
    
    // Detailed Results
    "ResultsNotAvailable": "Detailed results are not available or loading.",
    "ScoreFormatTemplate": "{0} / {1} points ({2}%)",
    "ExcellentPerformanceMessage": "Excellent! You've mastered this material.",
    "GreatPerformanceMessage": "Great job! You have a good understanding of the material.",
    "GoodPerformanceMessage": "Good effort! With a bit more study, you'll master this.",
    "AveragePerformanceMessage": "Keep practicing. You're making progress.",
    "PoorPerformanceMessage": "Don't give up! With more practice, you'll improve.",
    "QuestionResultsLabel": "Question Results",
    "QuestionDetailsLabel": "Question Details",
    "CorrectResultText": "Correct",
    "IncorrectResultText": "Incorrect",
    "YourAnswerLabel": "Your Answer:",
    
    "AddQuestionButtonTextShort": "Add",
    "RefreshButtonText": "Refresh",
    "DeleteSelectedText": "Delete Selected",
    "EditSelectedText": "Edit Selected",
    "EditQuestionTooltip": "Edit Question",
    "PreviewTooltip": "Preview",
    "DeleteTooltip": "Delete",
    "SearchQuestionsPlaceholder": "Search questions...",
    "FilterByCategoryPlaceholder": "Filter by category",
    "FilterByTypePlaceholder": "Filter by type",
    "AllCategoriesOption": "All Categories",
    "AllTypesOption": "All Types",
    "ItemsSelectedMessage": "{0} item(s) selected",
    "NoQuestionsFoundMessage": "No questions found. Try different search criteria or add new questions.",
    "ConfirmDeleteTitle": "Confirm Delete",
    "ConfirmDeleteSingleQuestion": "Are you sure you want to delete the question \"{0}\"?",
    "ConfirmDeleteSelectedQuestions": "Are you sure you want to delete {0} selected question(s)?",
    "DeletingLabel": "Deleting...",
    
    "RequireAllQuestionsLabel": "Require all questions to be answered",
    "NoQuestionsInCategoryMessage": "No questions found for this category.",
    "SubmittingQuizLabel": "Submitting quiz...",
    "SubmitQuizButtonText": "Submit Quiz",
    "AllQuestionsRequiredMessage": "Please answer all questions before submitting.",
    
    "MultipleChoiceType": "Multiple Choice",
    "TrueFalseType": "True/False",
    "MultiSelectType": "Multiple Select",
    "ShortAnswerType": "Short Answer",
    "MatchingType": "Matching"
  }
});